# This is a basic workflow to help you get started with Actions

name: EnvironmentWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - 'features/**'
      - 'issue/**'
  pull_request:
    branches:
      - main
      - 'features/**'
      - 'issue/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: TEST

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Java / JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # Build maven
    - name: Build with Maven
      env:
        SECRET: ${{ secrets.Greeting }}
      run: |
        mvn clean install

  job2:
    runs-on: ubuntu-latest
    environment: QA
    needs:
      - job1

    steps:
    - name: Send greeting2
      env:
        SECRET: ${{ secrets.Greeting }}
      run:  |
        echo "Job 2 running on QA"
        if [ $SECRET = "QaQaQa" ]; then echo "QA"; fi
      
  job3:
    runs-on: ubuntu-latest
    needs:
      - job2

    steps:
    - name: Send greeting3
      env:
        SECRET: ${{ secrets.Greeting }}
      run:  |
        echo "Job 3 running on no specific environment"
        if [ $SECRET = "RepoRepoRepo" ]; then echo "Repo"; fi
      
  job4:
    runs-on: ubuntu-latest
    environment: PROD
    needs:
      - job2

    steps:
    - name: Send greeting4
      env:
        SECRET: ${{ secrets.Greeting }}
      run:  |
        echo "Job 4 running on Prod"
        if [ $SECRET = "ProdProdProd" ]; then echo "Prod"; fi
